/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Event;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import modelo.Calle;

/**
 *
 * @author SAMAEL
 */
public class crearMapaPanel extends javax.swing.JPanel implements MouseMotionListener,MouseListener,KeyListener{

    int x=10;
    int y=5;
    Calle calle;
    
    
    
    public crearMapaPanel() {
        initComponents();
        addKeyListener(this);
        setFocusable(true);
        setFocusTraversalKeysEnabled(false);
        addMouseListener(this);
        addMouseMotionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(1120, 560));
        setPreferredSize(new java.awt.Dimension(1120, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

   
    

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        
         ///aca se grafica las lineas horizontales para la cuadricula
        g.drawLine(6, 0, 6, 560);
        for (int i = 0; i < x; i++) {
             g.drawLine((i*112)-6, 0, (i*112)-6, 560);
        }
        for (int i = 0; i < x; i++) {
             g.drawLine((i*112)+6, 0, (i*112)+6, 560);
        }
        g.drawLine(1114, 0, 1114, 560);
        
        
        ///aca se grafica las lineas  verticales para la cuadricula.
        g.drawLine(6, 0, 6, 560);
        for (int i = 0; i < y; i++) {
             g.drawLine(0, (i*112)-6, 1120, (i*112)-6);
        }
        for (int i = 0; i < y; i++) {
             g.drawLine(0, (i*112)+6, 1120, (i*112)+6);
        }
        g.drawLine(0,554 , 1120, 554);
        
        if(calle!=null)
        {
            g.drawImage(calle.getImagen().getImage(), calle.getX(), calle.getY(), calle.getAncho(), calle.getAlto(), this);
            g.setColor(Color.white);
            g.drawRect(calle.getX(), calle.getY(), calle.getAncho(), calle.getAlto());
        }
        
    }
    
    
    
   

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }

    public void setX(int x) {
        this.x = x;
    }

    public void setY(int y) {
        this.y = y;
    }
    
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseDragged(MouseEvent me) {
                
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        if(calle!=null)
        {
            calle.setX(e.getX());
            calle.setY(e.getY());
            repaint();
        }
    }

    @Override
    public void mouseClicked(MouseEvent me) {
        
    }

    @Override
    public void mousePressed(MouseEvent me) {
        
    }

    @Override
    public void mouseReleased(MouseEvent me) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        if(calle!=null)
        {
            calle.setX(e.getX());
            calle.setY(e.getY());
            repaint();
        }
    }

    @Override
    public void mouseExited(MouseEvent me) {
        
    }

    @Override
    public void keyTyped(KeyEvent ke) {
        
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        
    }
}
